/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package eu.mico.platform.anno4j.model.fam;


import org.openrdf.annotations.Iri;

import com.github.anno4j.model.impl.selector.TextPositionSelector;
import com.github.anno4j.model.impl.selector.TextQuoteSelector;
import com.github.anno4j.model.namespaces.OADM;

/**
 * The FAM encourages the use of both    
 * <a href="http://www.w3.org/ns/oa#TextPositionSelector">TextPositionSelector</a> and
 * <a href="http://www.w3.org/ns/oa#TextQuoteSelector">TextQuoteSelector</a> 
 * to describe selections in texts. This is because while the TextPositionSelector
 * is efficient for <code>text/plain</code> content often the plain text version
 * of a content is onyl generated by extracting text from rich text formats 
 * (html, xml, pdf, ...). In such cases the offsets of provided by the 
 * {@link TextPositionSelector} are not useful in the original content. But
 * prefix, selected and suffix information provided by the {@link TextQuoteSelector}
 * can still be used to locate the selected area in the original content.
 * 
 * @author Rupert Westenthaler
 * @see TextQuoteSelector
 * @see TextPositionSelector
 */
@Iri(OADM.SELECTOR_TEXT_POSITION)
public interface TextPositionQuoteSelector extends TextPositionSelector, TextQuoteSelector {

}
