#!/bin/sh
### BEGIN INIT INFO
# Provides: Hadoop HDFS
# Required-Start: sshd
# Required-Stop:
# Default-Start: 2 3 4 5
# Default-Stop:
# Short-Description:
### END INIT INFO

PATH=/sbin:/bin

USER=hadoop
export HADOOP_INSTALL=/opt/hadoop

case "$1" in
  start)
    /usr/bin/sudo -u ${USER} ${HADOOP_INSTALL}/sbin/start-dfs.sh
    ;;
  stop)
    /usr/bin/sudo -u ${USER} ${HADOOP_INSTALL}/sbin/stop-dfs.sh
    ;;
  restart|reload|force-reload|status)
    echo "Error: argument '$1' not supported" >&2
    exit 3
    ;;
  *)
    echo "Usage: $0 start|stop" >&2
    exit 3
    ;;
esac
