// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Event.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "Event.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace mico {
namespace event {
namespace model {

namespace {

const ::google::protobuf::Descriptor* RegistrationEvent_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  RegistrationEvent_reflection_ = NULL;
const ::google::protobuf::Descriptor* AnalysisEvent_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  AnalysisEvent_reflection_ = NULL;
const ::google::protobuf::Descriptor* ContentEvent_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ContentEvent_reflection_ = NULL;
const ::google::protobuf::Descriptor* DiscoveryEvent_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  DiscoveryEvent_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* Implementation_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* RegistrationType_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_Event_2eproto() {
  protobuf_AddDesc_Event_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "Event.proto");
  GOOGLE_CHECK(file != NULL);
  RegistrationEvent_descriptor_ = file->message_type(0);
  static const int RegistrationEvent_offsets_[6] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RegistrationEvent, serviceid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RegistrationEvent, queuename_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RegistrationEvent, provides_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RegistrationEvent, requires_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RegistrationEvent, language_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RegistrationEvent, type_),
  };
  RegistrationEvent_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      RegistrationEvent_descriptor_,
      RegistrationEvent::default_instance_,
      RegistrationEvent_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RegistrationEvent, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RegistrationEvent, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(RegistrationEvent));
  AnalysisEvent_descriptor_ = file->message_type(1);
  static const int AnalysisEvent_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AnalysisEvent, serviceid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AnalysisEvent, contentitemuri_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AnalysisEvent, objecturi_),
  };
  AnalysisEvent_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      AnalysisEvent_descriptor_,
      AnalysisEvent::default_instance_,
      AnalysisEvent_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AnalysisEvent, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AnalysisEvent, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(AnalysisEvent));
  ContentEvent_descriptor_ = file->message_type(2);
  static const int ContentEvent_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ContentEvent, contentitemuri_),
  };
  ContentEvent_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ContentEvent_descriptor_,
      ContentEvent::default_instance_,
      ContentEvent_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ContentEvent, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ContentEvent, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(ContentEvent));
  DiscoveryEvent_descriptor_ = file->message_type(3);
  static const int DiscoveryEvent_offsets_[1] = {
  };
  DiscoveryEvent_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      DiscoveryEvent_descriptor_,
      DiscoveryEvent::default_instance_,
      DiscoveryEvent_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DiscoveryEvent, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DiscoveryEvent, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(DiscoveryEvent));
  Implementation_descriptor_ = file->enum_type(0);
  RegistrationType_descriptor_ = file->enum_type(1);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_Event_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    RegistrationEvent_descriptor_, &RegistrationEvent::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    AnalysisEvent_descriptor_, &AnalysisEvent::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ContentEvent_descriptor_, &ContentEvent::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    DiscoveryEvent_descriptor_, &DiscoveryEvent::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_Event_2eproto() {
  delete RegistrationEvent::default_instance_;
  delete RegistrationEvent_reflection_;
  delete AnalysisEvent::default_instance_;
  delete AnalysisEvent_reflection_;
  delete ContentEvent::default_instance_;
  delete ContentEvent_reflection_;
  delete DiscoveryEvent::default_instance_;
  delete DiscoveryEvent_reflection_;
}

void protobuf_AddDesc_Event_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\013Event.proto\022\020mico.event.model\"\323\001\n\021Regi"
    "strationEvent\022\021\n\tserviceId\030\001 \002(\t\022\021\n\tqueu"
    "eName\030\002 \002(\t\022\020\n\010provides\030\003 \002(\t\022\020\n\010require"
    "s\030\004 \002(\t\0228\n\010language\030\005 \001(\0162 .mico.event.m"
    "odel.Implementation:\004JAVA\022:\n\004type\030\006 \001(\0162"
    "\".mico.event.model.RegistrationType:\010REG"
    "ISTER\"M\n\rAnalysisEvent\022\021\n\tserviceId\030\001 \002("
    "\t\022\026\n\016contentItemUri\030\002 \002(\t\022\021\n\tobjectUri\030\003"
    " \001(\t\"&\n\014ContentEvent\022\026\n\016contentItemUri\030\001"
    " \002(\t\"\020\n\016DiscoveryEvent*/\n\016Implementation"
    "\022\010\n\004JAVA\020\001\022\007\n\003CPP\020\002\022\n\n\006PYTHON\020\003*0\n\020Regis"
    "trationType\022\014\n\010REGISTER\020\001\022\016\n\nUNREGISTER\020"
    "\002B\036\n\034eu.mico.platform.event.model", 513);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "Event.proto", &protobuf_RegisterTypes);
  RegistrationEvent::default_instance_ = new RegistrationEvent();
  AnalysisEvent::default_instance_ = new AnalysisEvent();
  ContentEvent::default_instance_ = new ContentEvent();
  DiscoveryEvent::default_instance_ = new DiscoveryEvent();
  RegistrationEvent::default_instance_->InitAsDefaultInstance();
  AnalysisEvent::default_instance_->InitAsDefaultInstance();
  ContentEvent::default_instance_->InitAsDefaultInstance();
  DiscoveryEvent::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_Event_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_Event_2eproto {
  StaticDescriptorInitializer_Event_2eproto() {
    protobuf_AddDesc_Event_2eproto();
  }
} static_descriptor_initializer_Event_2eproto_;
const ::google::protobuf::EnumDescriptor* Implementation_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Implementation_descriptor_;
}
bool Implementation_IsValid(int value) {
  switch(value) {
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* RegistrationType_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return RegistrationType_descriptor_;
}
bool RegistrationType_IsValid(int value) {
  switch(value) {
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}


// ===================================================================

#ifndef _MSC_VER
const int RegistrationEvent::kServiceIdFieldNumber;
const int RegistrationEvent::kQueueNameFieldNumber;
const int RegistrationEvent::kProvidesFieldNumber;
const int RegistrationEvent::kRequiresFieldNumber;
const int RegistrationEvent::kLanguageFieldNumber;
const int RegistrationEvent::kTypeFieldNumber;
#endif  // !_MSC_VER

RegistrationEvent::RegistrationEvent()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void RegistrationEvent::InitAsDefaultInstance() {
}

RegistrationEvent::RegistrationEvent(const RegistrationEvent& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void RegistrationEvent::SharedCtor() {
  _cached_size_ = 0;
  serviceid_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  queuename_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  provides_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  requires_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  language_ = 1;
  type_ = 1;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

RegistrationEvent::~RegistrationEvent() {
  SharedDtor();
}

void RegistrationEvent::SharedDtor() {
  if (serviceid_ != &::google::protobuf::internal::kEmptyString) {
    delete serviceid_;
  }
  if (queuename_ != &::google::protobuf::internal::kEmptyString) {
    delete queuename_;
  }
  if (provides_ != &::google::protobuf::internal::kEmptyString) {
    delete provides_;
  }
  if (requires_ != &::google::protobuf::internal::kEmptyString) {
    delete requires_;
  }
  if (this != default_instance_) {
  }
}

void RegistrationEvent::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* RegistrationEvent::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return RegistrationEvent_descriptor_;
}

const RegistrationEvent& RegistrationEvent::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_Event_2eproto();
  return *default_instance_;
}

RegistrationEvent* RegistrationEvent::default_instance_ = NULL;

RegistrationEvent* RegistrationEvent::New() const {
  return new RegistrationEvent;
}

void RegistrationEvent::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_serviceid()) {
      if (serviceid_ != &::google::protobuf::internal::kEmptyString) {
        serviceid_->clear();
      }
    }
    if (has_queuename()) {
      if (queuename_ != &::google::protobuf::internal::kEmptyString) {
        queuename_->clear();
      }
    }
    if (has_provides()) {
      if (provides_ != &::google::protobuf::internal::kEmptyString) {
        provides_->clear();
      }
    }
    if (has_requires()) {
      if (requires_ != &::google::protobuf::internal::kEmptyString) {
        requires_->clear();
      }
    }
    language_ = 1;
    type_ = 1;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool RegistrationEvent::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string serviceId = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_serviceid()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->serviceid().data(), this->serviceid().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_queueName;
        break;
      }

      // required string queueName = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_queueName:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_queuename()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->queuename().data(), this->queuename().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_provides;
        break;
      }

      // required string provides = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_provides:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_provides()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->provides().data(), this->provides().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(34)) goto parse_requires;
        break;
      }

      // required string requires = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_requires:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_requires()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->requires().data(), this->requires().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(40)) goto parse_language;
        break;
      }

      // optional .mico.event.model.Implementation language = 5 [default = JAVA];
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_language:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::mico::event::model::Implementation_IsValid(value)) {
            set_language(static_cast< ::mico::event::model::Implementation >(value));
          } else {
            mutable_unknown_fields()->AddVarint(5, value);
          }
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(48)) goto parse_type;
        break;
      }

      // optional .mico.event.model.RegistrationType type = 6 [default = REGISTER];
      case 6: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_type:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::mico::event::model::RegistrationType_IsValid(value)) {
            set_type(static_cast< ::mico::event::model::RegistrationType >(value));
          } else {
            mutable_unknown_fields()->AddVarint(6, value);
          }
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void RegistrationEvent::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required string serviceId = 1;
  if (has_serviceid()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->serviceid().data(), this->serviceid().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->serviceid(), output);
  }

  // required string queueName = 2;
  if (has_queuename()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->queuename().data(), this->queuename().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->queuename(), output);
  }

  // required string provides = 3;
  if (has_provides()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->provides().data(), this->provides().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      3, this->provides(), output);
  }

  // required string requires = 4;
  if (has_requires()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->requires().data(), this->requires().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      4, this->requires(), output);
  }

  // optional .mico.event.model.Implementation language = 5 [default = JAVA];
  if (has_language()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      5, this->language(), output);
  }

  // optional .mico.event.model.RegistrationType type = 6 [default = REGISTER];
  if (has_type()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      6, this->type(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* RegistrationEvent::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required string serviceId = 1;
  if (has_serviceid()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->serviceid().data(), this->serviceid().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->serviceid(), target);
  }

  // required string queueName = 2;
  if (has_queuename()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->queuename().data(), this->queuename().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->queuename(), target);
  }

  // required string provides = 3;
  if (has_provides()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->provides().data(), this->provides().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->provides(), target);
  }

  // required string requires = 4;
  if (has_requires()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->requires().data(), this->requires().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->requires(), target);
  }

  // optional .mico.event.model.Implementation language = 5 [default = JAVA];
  if (has_language()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      5, this->language(), target);
  }

  // optional .mico.event.model.RegistrationType type = 6 [default = REGISTER];
  if (has_type()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      6, this->type(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int RegistrationEvent::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string serviceId = 1;
    if (has_serviceid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->serviceid());
    }

    // required string queueName = 2;
    if (has_queuename()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->queuename());
    }

    // required string provides = 3;
    if (has_provides()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->provides());
    }

    // required string requires = 4;
    if (has_requires()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->requires());
    }

    // optional .mico.event.model.Implementation language = 5 [default = JAVA];
    if (has_language()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->language());
    }

    // optional .mico.event.model.RegistrationType type = 6 [default = REGISTER];
    if (has_type()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->type());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void RegistrationEvent::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const RegistrationEvent* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const RegistrationEvent*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void RegistrationEvent::MergeFrom(const RegistrationEvent& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_serviceid()) {
      set_serviceid(from.serviceid());
    }
    if (from.has_queuename()) {
      set_queuename(from.queuename());
    }
    if (from.has_provides()) {
      set_provides(from.provides());
    }
    if (from.has_requires()) {
      set_requires(from.requires());
    }
    if (from.has_language()) {
      set_language(from.language());
    }
    if (from.has_type()) {
      set_type(from.type());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void RegistrationEvent::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void RegistrationEvent::CopyFrom(const RegistrationEvent& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RegistrationEvent::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000000f) != 0x0000000f) return false;

  return true;
}

void RegistrationEvent::Swap(RegistrationEvent* other) {
  if (other != this) {
    std::swap(serviceid_, other->serviceid_);
    std::swap(queuename_, other->queuename_);
    std::swap(provides_, other->provides_);
    std::swap(requires_, other->requires_);
    std::swap(language_, other->language_);
    std::swap(type_, other->type_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata RegistrationEvent::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = RegistrationEvent_descriptor_;
  metadata.reflection = RegistrationEvent_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int AnalysisEvent::kServiceIdFieldNumber;
const int AnalysisEvent::kContentItemUriFieldNumber;
const int AnalysisEvent::kObjectUriFieldNumber;
#endif  // !_MSC_VER

AnalysisEvent::AnalysisEvent()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void AnalysisEvent::InitAsDefaultInstance() {
}

AnalysisEvent::AnalysisEvent(const AnalysisEvent& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void AnalysisEvent::SharedCtor() {
  _cached_size_ = 0;
  serviceid_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  contentitemuri_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  objecturi_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

AnalysisEvent::~AnalysisEvent() {
  SharedDtor();
}

void AnalysisEvent::SharedDtor() {
  if (serviceid_ != &::google::protobuf::internal::kEmptyString) {
    delete serviceid_;
  }
  if (contentitemuri_ != &::google::protobuf::internal::kEmptyString) {
    delete contentitemuri_;
  }
  if (objecturi_ != &::google::protobuf::internal::kEmptyString) {
    delete objecturi_;
  }
  if (this != default_instance_) {
  }
}

void AnalysisEvent::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* AnalysisEvent::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return AnalysisEvent_descriptor_;
}

const AnalysisEvent& AnalysisEvent::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_Event_2eproto();
  return *default_instance_;
}

AnalysisEvent* AnalysisEvent::default_instance_ = NULL;

AnalysisEvent* AnalysisEvent::New() const {
  return new AnalysisEvent;
}

void AnalysisEvent::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_serviceid()) {
      if (serviceid_ != &::google::protobuf::internal::kEmptyString) {
        serviceid_->clear();
      }
    }
    if (has_contentitemuri()) {
      if (contentitemuri_ != &::google::protobuf::internal::kEmptyString) {
        contentitemuri_->clear();
      }
    }
    if (has_objecturi()) {
      if (objecturi_ != &::google::protobuf::internal::kEmptyString) {
        objecturi_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool AnalysisEvent::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string serviceId = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_serviceid()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->serviceid().data(), this->serviceid().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_contentItemUri;
        break;
      }

      // required string contentItemUri = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_contentItemUri:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_contentitemuri()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->contentitemuri().data(), this->contentitemuri().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_objectUri;
        break;
      }

      // optional string objectUri = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_objectUri:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_objecturi()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->objecturi().data(), this->objecturi().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void AnalysisEvent::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required string serviceId = 1;
  if (has_serviceid()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->serviceid().data(), this->serviceid().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->serviceid(), output);
  }

  // required string contentItemUri = 2;
  if (has_contentitemuri()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->contentitemuri().data(), this->contentitemuri().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->contentitemuri(), output);
  }

  // optional string objectUri = 3;
  if (has_objecturi()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->objecturi().data(), this->objecturi().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      3, this->objecturi(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* AnalysisEvent::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required string serviceId = 1;
  if (has_serviceid()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->serviceid().data(), this->serviceid().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->serviceid(), target);
  }

  // required string contentItemUri = 2;
  if (has_contentitemuri()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->contentitemuri().data(), this->contentitemuri().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->contentitemuri(), target);
  }

  // optional string objectUri = 3;
  if (has_objecturi()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->objecturi().data(), this->objecturi().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->objecturi(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int AnalysisEvent::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string serviceId = 1;
    if (has_serviceid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->serviceid());
    }

    // required string contentItemUri = 2;
    if (has_contentitemuri()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->contentitemuri());
    }

    // optional string objectUri = 3;
    if (has_objecturi()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->objecturi());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void AnalysisEvent::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const AnalysisEvent* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const AnalysisEvent*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void AnalysisEvent::MergeFrom(const AnalysisEvent& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_serviceid()) {
      set_serviceid(from.serviceid());
    }
    if (from.has_contentitemuri()) {
      set_contentitemuri(from.contentitemuri());
    }
    if (from.has_objecturi()) {
      set_objecturi(from.objecturi());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void AnalysisEvent::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void AnalysisEvent::CopyFrom(const AnalysisEvent& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AnalysisEvent::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  return true;
}

void AnalysisEvent::Swap(AnalysisEvent* other) {
  if (other != this) {
    std::swap(serviceid_, other->serviceid_);
    std::swap(contentitemuri_, other->contentitemuri_);
    std::swap(objecturi_, other->objecturi_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata AnalysisEvent::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = AnalysisEvent_descriptor_;
  metadata.reflection = AnalysisEvent_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int ContentEvent::kContentItemUriFieldNumber;
#endif  // !_MSC_VER

ContentEvent::ContentEvent()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void ContentEvent::InitAsDefaultInstance() {
}

ContentEvent::ContentEvent(const ContentEvent& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void ContentEvent::SharedCtor() {
  _cached_size_ = 0;
  contentitemuri_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ContentEvent::~ContentEvent() {
  SharedDtor();
}

void ContentEvent::SharedDtor() {
  if (contentitemuri_ != &::google::protobuf::internal::kEmptyString) {
    delete contentitemuri_;
  }
  if (this != default_instance_) {
  }
}

void ContentEvent::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ContentEvent::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ContentEvent_descriptor_;
}

const ContentEvent& ContentEvent::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_Event_2eproto();
  return *default_instance_;
}

ContentEvent* ContentEvent::default_instance_ = NULL;

ContentEvent* ContentEvent::New() const {
  return new ContentEvent;
}

void ContentEvent::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_contentitemuri()) {
      if (contentitemuri_ != &::google::protobuf::internal::kEmptyString) {
        contentitemuri_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool ContentEvent::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string contentItemUri = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_contentitemuri()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->contentitemuri().data(), this->contentitemuri().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void ContentEvent::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required string contentItemUri = 1;
  if (has_contentitemuri()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->contentitemuri().data(), this->contentitemuri().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->contentitemuri(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* ContentEvent::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required string contentItemUri = 1;
  if (has_contentitemuri()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->contentitemuri().data(), this->contentitemuri().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->contentitemuri(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int ContentEvent::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string contentItemUri = 1;
    if (has_contentitemuri()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->contentitemuri());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ContentEvent::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const ContentEvent* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const ContentEvent*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ContentEvent::MergeFrom(const ContentEvent& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_contentitemuri()) {
      set_contentitemuri(from.contentitemuri());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void ContentEvent::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ContentEvent::CopyFrom(const ContentEvent& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ContentEvent::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void ContentEvent::Swap(ContentEvent* other) {
  if (other != this) {
    std::swap(contentitemuri_, other->contentitemuri_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata ContentEvent::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ContentEvent_descriptor_;
  metadata.reflection = ContentEvent_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
#endif  // !_MSC_VER

DiscoveryEvent::DiscoveryEvent()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void DiscoveryEvent::InitAsDefaultInstance() {
}

DiscoveryEvent::DiscoveryEvent(const DiscoveryEvent& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void DiscoveryEvent::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

DiscoveryEvent::~DiscoveryEvent() {
  SharedDtor();
}

void DiscoveryEvent::SharedDtor() {
  if (this != default_instance_) {
  }
}

void DiscoveryEvent::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* DiscoveryEvent::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return DiscoveryEvent_descriptor_;
}

const DiscoveryEvent& DiscoveryEvent::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_Event_2eproto();
  return *default_instance_;
}

DiscoveryEvent* DiscoveryEvent::default_instance_ = NULL;

DiscoveryEvent* DiscoveryEvent::New() const {
  return new DiscoveryEvent;
}

void DiscoveryEvent::Clear() {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool DiscoveryEvent::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
        ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
      return true;
    }
    DO_(::google::protobuf::internal::WireFormat::SkipField(
          input, tag, mutable_unknown_fields()));
  }
  return true;
#undef DO_
}

void DiscoveryEvent::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* DiscoveryEvent::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int DiscoveryEvent::ByteSize() const {
  int total_size = 0;

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void DiscoveryEvent::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const DiscoveryEvent* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const DiscoveryEvent*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void DiscoveryEvent::MergeFrom(const DiscoveryEvent& from) {
  GOOGLE_CHECK_NE(&from, this);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void DiscoveryEvent::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DiscoveryEvent::CopyFrom(const DiscoveryEvent& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DiscoveryEvent::IsInitialized() const {

  return true;
}

void DiscoveryEvent::Swap(DiscoveryEvent* other) {
  if (other != this) {
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata DiscoveryEvent::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = DiscoveryEvent_descriptor_;
  metadata.reflection = DiscoveryEvent_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace model
}  // namespace event
}  // namespace mico

// @@protoc_insertion_point(global_scope)
