PREFIX mico: <http://www.mico-project.eu/ns/platform/1.0/schema#>
PREFIX ldp: <http://www.w3.org/ns/ldp#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

INSERT DATA {
  GRAPH <$(ci)-metadata> {
    <$(ci)> mico:hasContentPart <$(cp)> .
    <$(ci)> ldp:contains <$(cp)> .
    <$(cp)> rdf:type mico:ContentPart .
  }
}