# Inputs:
#   $(body) : The uri of the body
#   $(conf) : The confidence value
#   $(detection) : The detected person
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX mico: <http://www.mico-project.eu/ns/platform/1.0/schema#>

INSERT DATA {
  GRAPH <$(body)> {
    <$(body)> rdf:type mico:FaceRecognitionBody .
    <$(body)> mico:hasConfidence "$(conf)" .
    <$(body)> rdf:value "$(detection)" .
  }
}