# Inputs:
#   $(ci) : The uri of the content item
#   $(body) : The uri of the body
#   $(value) : Extractor result as string
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX mico: <http://www.mico-project.eu/ns/platform/1.0/schema#>

INSERT DATA {
  GRAPH <$(ci)-metadata> {
    <$(body)> rdf:type mico:TVSShotBoundaryFrameBody .
  }
}