# Inputs:
#   $(cp) : The uri of the content part
#   $(an) : The uri of the annotation
#   $(body) : The uri of the body
#   $(target) : The uri of the target
PREFIX mico: <http://www.mico-project.eu/ns/platform/1.0/schema#>
PREFIX ldp: <http://www.w3.org/ns/ldp#>
PREFIX oa: <http://www.w3.org/ns/oa#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

INSERT DATA {
  GRAPH <$(cp)-metadata> {
    <$(cp)> mico:hasContent <$(an)> .
    <$(cp)> ldp:contains <$(an)> .
    <$(an)> rdf:type oa:Annotation
    <$(an)> oa:hasBody <$(body)>
    <$(an)> oa:hasTarget <$(target)>
    <$(target)> rdf:type oa:SpecificResource
  }
}