#!/bin/sh
# postinst script for mico-extractor-wordcount

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package

NAME="mico-extractor-wordcount"
GROUP="mico"
USER="mico"
REGISTRATION_FILE="/usr/share/mico/extractor-registrations/$NAME.registration.xml"
DATADIR=/var/lib/mico-extractor-wordcount

case "$1" in
    configure)

    mkdir -p /var/log/$NAME
    mkdir -p $DATADIR
    mkdir -p $DATADIR/dist

    chown $USER:$GROUP -R /var/log/$NAME
    chown $USER:$GROUP -R /var/lib/$NAME

    #######################################
    # register extractor on mico platform #
    # Source debconf library.
    . /usr/share/debconf/confmodule

    db_get mico-extractor-registration/registration-url
    REG_SVC="$RET"

    /usr/bin/mico-extractor-registration "$REG_SVC" "$REGISTRATION_FILE"

    db_stop

    ;;
    
    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# shamelessly copied from debian apache2 package...
if [ -x "/etc/init.d/mico-extractor-wordcount" ] || [ -e "/etc/init/mico-extractor-wordcount.conf" ]; then
    if [ ! -e "/etc/init/mico-extractor-wordcount.conf" ]; then
        update-rc.d mico-extractor-wordcount defaults >/dev/null
    fi
    invoke-rc.d mico-extractor-wordcount start || exit $?
fi

exit 0
