#!/bin/sh
# prerm script for mico-extractor-wordcount

set -e

# summary of how this script can be called:
#        * <prerm> `remove'
#        * <old-prerm> `upgrade' <new-version>
#        * <new-prerm> `failed-upgrade' <old-version>
#        * <conflictor's-prerm> `remove' `in-favour' <package> <new-version>
#        * <deconfigured's-prerm> `deconfigure' `in-favour'
#          <package-being-installed> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package

EXTRACTOR_ID=mico-extractor-wordcount

case "$1" in
    remove|upgrade|deconfigure)

        . /usr/share/debconf/confmodule

        db_get mico-extractor-registration/registration-url
        REG_SVC="$RET"

        #un-register
        /usr/bin/mico-extractor-registration "$REG_SVC" "$EXTRACTOR_ID" "--remove" || echo "WARN: un-registration of $EXTRACTOR_ID failed"

        db_stop

    ;;

    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

if [ -x "/etc/init.d/mico-extractor-wordcount" ] || [ -e "/etc/init/mico-extractor-wordcount.conf" ]; then
        invoke-rc.d mico-extractor-wordcount stop || exit $?
fi

exit 0
