#!/bin/sh

# Source debconf library.
. /usr/share/debconf/confmodule

db_version 2.0

db_settitle mico-marmotta/title

# set a default random password
db_subst mico-marmotta/database-password dbpass `pwgen -ncs 12`

db_input critical mico-marmotta/database-name || true
db_input critical mico-marmotta/database-user || true
db_input critical mico-marmotta/database-password || true
db_input critical mico-marmotta/create-database || true

db_go || true
