#!/bin/sh

# Source debconf library.
. /usr/share/debconf/confmodule

if [ -f /usr/bin/pwgen ]; then

    if ip -4 -o addr show eth1 >/dev/null 2>&1; then
      MYIP=`ip -4 -o addr show dev eth1 |  awk '{split($4,a,"/");print a[1]}'`
    else
      MYIP=`ip -4 -o addr show dev eth0 |  awk '{split($4,a,"/");print a[1]}'`
    fi

    db_version 2.0

    db_settitle mico-marmotta/title

    db_input critical mico-marmotta/database-name || true
    db_input critical mico-marmotta/database-user || true

    db_set mico-marmotta/database-password `pwgen -ncs 12`
    db_input critical mico-marmotta/database-password || true

    db_input critical mico-marmotta/create-database || true

    db_set mico-marmotta/host-name "$MYIP"
    db_input critical mico-marmotta/host-name || true

    db_go || true

fi